data_path: datasets/mooc_item/
dataset: files
checkpoint_dir: saved/
results_dir: datasets/mooc_item/results/
benchmark_filename: ['train', 'train_target', 'test_target']
# dataset config : Sequential Recommendation
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id,rating, timestamp, item_id_list]
MAX_ITEM_LIST_LENGTH: 160
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: "_list"


test_file: './datasets/mooc_item/files/files.test_target.inter'
run_num: 3
next_item: True

# model config
model: GRU4Rec
embedding_size: 100
hidden_size: 256
num_layers: 1
dropout_prob: 0.3
loss_type: 'CE'

# Training and evaluation config
epochs: 30
train_batch_size: 64
eval_batch_size: 64
train_neg_sample_args: ~
eval_args:
    group_by: user
    order: TO
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: MRR@10
metric_decimal_place: 4